print('+---------------------------------------------------------------------+')
print('|                                                      February 2023  |')
print('|                                                       Leon, Spain   |')
print('|  Dear Self,                                                         |')
print('|                                                                     |')
print('|      Build the learn to code platform that you always dreamed of.   |')
print('|      Give more than you take.                                       |')
print('|      Care > capital.                                                |')
print('|      Five-second funerals for all the Ls.                           |')
print('|      And always get back up.                                        |')
print('|                                                                     |')
print('|                                              Mou      🤠            |')
print('|                                                                     |')
print('+---------------------------------------------------------------------+')